// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxgnJyeyCyGWMu_Gc29BC83_95kYK67Uo',
    appId: '1:671942965726:web:8666fa6af6cfe030ce854f',
    messagingSenderId: '671942965726',
    projectId: 'tobeto-clone',
    authDomain: 'tobeto-clone.firebaseapp.com',
    storageBucket: 'tobeto-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUwkVQl5lxdCM43zsyhoO2rZNpehXnlM',
    appId: '1:671942965726:android:bc817fab5fa33407ce854f',
    messagingSenderId: '671942965726',
    projectId: 'tobeto-clone',
    storageBucket: 'tobeto-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYaR351TkCq0WOt3d8RFjPAIxwvO5DB4Q',
    appId: '1:671942965726:ios:90430ae5f84bfc26ce854f',
    messagingSenderId: '671942965726',
    projectId: 'tobeto-clone',
    storageBucket: 'tobeto-clone.appspot.com',
    iosBundleId: 'com.example.tobetoclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYaR351TkCq0WOt3d8RFjPAIxwvO5DB4Q',
    appId: '1:671942965726:ios:b141c43fd1b12128ce854f',
    messagingSenderId: '671942965726',
    projectId: 'tobeto-clone',
    storageBucket: 'tobeto-clone.appspot.com',
    iosBundleId: 'com.example.tobetoclone.RunnerTests',
  );
}
